//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaHitss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
            this.CinePelis = new HashSet<CinePeli>();
            this.Historials = new HashSet<Historial>();
            this.PeliHoras = new HashSet<PeliHora>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public string Clasificacion { get; set; }
        public System.TimeSpan Duracion { get; set; }
        public string Sinopsis { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<System.DateTime> fechaProyeccion { get; set; }
        public string Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CinePeli> CinePelis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial> Historials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeliHora> PeliHoras { get; set; }
    }
}
